<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0M17UIVA" failures="1" tests="9" name="D:/repo1/clone/TestFolder/Demo/Sept_3_2024_Maven_Project" time="0.114" errors="0" timestamp="2024-12-11T20:18:41 IST">
  <testcase classname="testng.basicoftestng.BeforeMethodExample" name="test_1" time="0.001"/>
  <testcase classname="testng.basicoftestng.BeforeMethodExample" name="test_2" time="0.008">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase classname="testng.basicoftestng.BeforeMethodExample" name="test_2" time="0.001">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase classname="testng.basicoftestng.BeforeMethodExample" name="test_2" time="0.001">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase classname="testng.basicoftestng.BeforeMethodExample" name="test_2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testng.basicoftestng.BeforeMethodExample.test_2(BeforeMethodExample.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- test_2 -->
  <testcase classname="testng.basicoftestng.BeforeMethodExample" name="test_3" time="0.0"/>
  <testcase classname="testng.basicoftestng.DependsOnGroupsExample" name="verifyPayments" time="0.001"/>
  <testcase classname="testng.basicoftestng.DependsOnGroupsExample" name="verifyReports" time="0.0"/>
  <testcase classname="testng.basicoftestng.DependsOnGroupsExample" name="verifyExecution" time="0.0"/>
</testsuite> <!-- D:/repo1/clone/TestFolder/Demo/Sept_3_2024_Maven_Project -->
